#
############################################################################
#Set id based on whoami.  Instructor files identified with extention prof
############################################################################

        set own = `whoami | cut -c1-5`     
        set pth = "/class/has/eng/$own/"

        set id = `whoami | cut -c6-7`     
        	if  $id == "" then
            	set id = prof
        	endif

############################################################################
#  Greeting
############################################################################

						# SET GREETING FOR ID MENU
set check = `date|sed 's/  / /g'|sed 's/ /:/g'|  cut -d":" -f4`  

	if ( $check < 12 ) then 
     	    set greet = "Good morning"

	else if ($check <= 18 ) then
     	    set greet = "Good afternoon"

	else set greet = "Good evening"
        endif

############################################################################
#Print menu of choices
############################################################################
while (1)
begin:
/person/has/eng/smhibbs/class.bin/menu.1

echo -n "$greet.  Please enter an option from the menu above. "

     set resp = $<
     switch ($resp)
     
		case g:  		# GRAB 
        	grab:
        clear
        echo 
        ls "$pth"share
        echo 
        echo -n "Grab which file? "
        set file=$<
        cp "$pth"share/$file  $file
        echo 
        echo -n "Grab another? (N)"     
        set resp = $<
        if (( $resp == y ) || ( $resp == Y )) then
        goto grab
        endif
        breaksw

     
		case s:   		# SHARE 
        		share:
        		echo 
                        ls
                        echo 
        		echo -n "Share which file? "
        		set file=$<
                        echo $file
        		cp ~/$file "$pth"share/$file.$id
        		chmod +r  "$pth"share/$file.$id
                        echo 
        		echo -n "Share another? (N)"     
        		set resp = $<
        		if (( $resp == y ) || ( $resp == Y )) then
        			goto share
        		endif
        	breaksw
                  
         	 
		case x: 		# EXIT TO SHELL
                exit
		breaksw

		case b:   		# SUBMIT
        		submit:
                        echo  
                        ls
                        echo 
        		echo -n "Submit which file? "
        		set file=$<
                        echo $file
        		cp ~/$file "$pth"box
                        echo 
        		echo -n "Submit another file? (N)"     
        		set resp = $<
        		if (( $resp == y ) || ( $resp == Y )) then
        			goto share
        		endif
                 
       endsw
end


